# Generated by Django 5.1.1 on 2024-11-16 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='data',
            new_name='data_postagem',
        ),
    ]
